### ISSUE TITLE
Syntax for anonymous functions overly restrictive

### ISSUE THREAD

**Issue by freddie-freeloader** [koka-lang/koka#86] opened 2020-01-17 14:09 UTC
Currently, the parser works the following way:

```
> val x = (fun(x) { x })
x : forall<a> (x : a) -> a

> val x = (fun (x) { x })
           ^
((2),10): error: invalid syntax
 unexpected keyword fun
 expecting expression or ")"
```

This seems to me overly restrictive and the error message doesn't help here either.

**Comment by dhil** [comment] 2020-01-17 15:52
I think this is a duplicate of #44.

**Comment by freddie-freeloader** [comment] 2020-01-17 16:24
Sorry, for not making a clearer suggestion.

The only difference between the two versions is the white space after `fun`.

I'd suggest that zero *or more* white spaces would be allowed at this location.

**Comment by dhil** [comment] 2020-01-21 19:08
Thank you for the clarification.

According to the specification this behaviour is **not** a bug. The specification says the following about production rule matching:

> [..] the order of the productions is not important and at each point the *longest matching lexeme* is preferred [..] a prefix or postfix pattern is included when considering a longest match.

The [rule for anonymous functions](https://koka-lang.github.io/koka/doc/kokaspec.html#sec-identifiers) reads (here I have quoted lexemes for clarity):
```
funanon ::= ('fun' | 'function')< '<' | '(' >       (anonymous functions must be followed by a '(' or '<')) 
```
Thus no space is allowed between `fun`/`function` and `<`/`(` as that would break the longest matching lexeme rule.

As I mentioned in #44, an argument can be made for relaxing such syntactic constraints, however, as per the current language specification the program
```koka
val x = (fun (x) { x })
```
is not a valid Koka program.

**Closed** 2020-07-17 12:04 UTC
