### ISSUE TITLE
Recursive Effect Types

### ISSUE THREAD

**Issue by thwfhk** [koka-lang/koka#565] opened 2024-07-23 18:50 UTC
The following definition of recursive effect types works well with Koka 3.0.4.
```
rec effect receff
  ctl receff(p : () -> <receff> a) : a
```
However, for any version after 3.0.4, I get the following internal error:
```
internal error: label has not kind X: (TCon (TypeCon {typeconName = mytests/test-he/receff, typeconKind = KApp (KApp (KCon (->)) (KCon E)) (KApp (KApp (KCon (->)) (KCon V)) (KCon V))}),TCon (TypeCon {typeconName = std/core/types/total, typeconKind = KCon E}))
CallStack (from HasCallStack):
  error, called at src/Common/Failure.hs:46:12 in koka-3.1.2-7xynmeak7qO4RkIQOuOqWL:Common.Failure
  raise, called at src/Common/Failure.hs:32:5 in koka-3.1.2-7xynmeak7qO4RkIQOuOqWL:Common.Failure
  failure, called at src/Common/Failure.hs:28:11 in koka-3.1.2-7xynmeak7qO4RkIQOuOqWL:Common.Failure
  assertion, called at src/Type/Type.hs:744:5 in koka-3.1.2-7xynmeak7qO4RkIQOuOqWL:Type.Type
  appEffectExtend, called at src/Type/Type.hs:679:14 in koka-3.1.2-7xynmeak7qO4RkIQOuOqWL:Type.Type
  effectExtend, called at src/Type/Type.hs:562:14 in koka-3.1.2-7xynmeak7qO4RkIQOuOqWL:Type.Type
```
I wonder if this is a bug or what is the correct way to define recursive effect types in koka now.

**Comment by anfelor** [comment] 2024-07-23 18:58
Thanks Wenhao! This is a duplicate of #483

**Closed as completed by anfelor** 2024-07-23 18:58 UTC
