### ISSUE TITLE
Running koka problems on freebsd

### ISSUE THREAD

**Issue by devosalain** [koka-lang/koka#218] opened 2021-11-21 05:28 UTC
Compilation using cabal went perfect.
After starting koka with:
cabal new-run koka:
> :t "a"
check : interactive
string
<---------------Everything ok
>println("hi koka")
<-----------------
> println("Hi koka")
check  : interactive
check  : interactive
compile: kklib from: /usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib
In file included from /usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/all.c:20:
/usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/random.c: In function 'kk_os_random_buf':
/usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/random.c:305:3: warning: implicit declaration of function 'arc4random_buf'; did you mean 'kk_os_random_buf'? [-Wimplicit-function-declaration]
  305 |   arc4random_buf(buf, buf_len);
      |   ^~~~~~~~~~~~~~
      |   kk_os_random_buf
In file included from /usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/../mimalloc/src/static.c:25,
                 from /usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/all.c:29:
/usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/../mimalloc/src/os.c: In function 'mi_unix_mmap':
/usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/../mimalloc/src/os.c:396:26: error: 'MAP_ANON' undeclared (first use in this function); did you mean 'MAX_CANON'?
  396 |   #define MAP_ANONYMOUS  MAP_ANON
      |                          ^~~~~~~~
/usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/../mimalloc/src/os.c:401:29: note: in expansion of macro 'MAP_ANONYMOUS'
  401 |   int flags = MAP_PRIVATE | MAP_ANONYMOUS | MAP_NORESERVE;
      |                             ^~~~~~~~~~~~~
/usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/../mimalloc/src/os.c:396:26: note: each undeclared identifier is reported only once for each function it appears in
  396 |   #define MAP_ANONYMOUS  MAP_ANON
      |                          ^~~~~~~~
/usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/../mimalloc/src/os.c:401:29: note: in expansion of macro 'MAP_ANONYMOUS'
  401 |   int flags = MAP_PRIVATE | MAP_ANONYMOUS | MAP_NORESERVE;
      |                             ^~~~~~~~~~~~~
/usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/../mimalloc/src/os.c: In function 'mi_os_commitx':
/usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/../mimalloc/src/os.c:396:26: error: 'MAP_ANON' undeclared (first use in this function); did you mean 'MAX_CANON'?
  396 |   #define MAP_ANONYMOUS  MAP_ANON
      |                          ^~~~~~~~
/usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/../mimalloc/src/os.c:784:72: note: in expansion of macro 'MAP_ANONYMOUS'
  784 |     void* p = mmap(start, csize, PROT_NONE, (MAP_FIXED | MAP_PRIVATE | MAP_ANONYMOUS | MAP_NORESERVE), fd, 0);
      |                                                                        ^~~~~~~~~~~~~
/usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/../mimalloc/src/os.c: In function 'mi_os_resetx':
/usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/../mimalloc/src/os.c:881:13: warning: implicit declaration of function 'madvise'; did you mean 'raise'? [-Wimplicit-function-declaration]
  881 |   int err = madvise(start, csize, MADV_DONTNEED);
      |             ^~~~~~~
      |             raise
/usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/../mimalloc/src/os.c:881:35: error: 'MADV_DONTNEED' undeclared (first use in this function); did you mean 'POSIX_MADV_DONTNEED'?
  881 |   int err = madvise(start, csize, MADV_DONTNEED);
      |                                   ^~~~~~~~~~~~~
      |                                   POSIX_MADV_DONTNEED
failure during code generation:
  error  : command failed (exit code 1)
  command: /usr/local/bin/gcc -Wall -Wextra -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-variable -Wno-unused-value -Wno-missing-field-initializers -Wpointer-arith -Wshadow -Wstrict-aliasing -Wno-unused-but-set-variable -g -O1 -c -I /usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/include -I /installed/x64-freebsd/include -I /usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/mimalloc/include -DKK_MIMALLOC "-DKK_COMP_VERSION=\"2.3.2\"" "-DKK_CC_NAME=\"gcc\"" -o /tmp/.koka/v2.3.2/gcc-debug/kklib.o /usr/home/x/Dirs/Src/languages/koka/koka/koka/kklib/src/all.c

Versions:
-OS      -----> FreeBSD 13.0-RELEASE-p5
-gcc -v:  ----> 11.2.0
-cc -v    -----> clang 11.0.1
-ghc --version ----> 8.10.7
-cabal --version ---> 3.4.0.0

**Comment by daanx** [comment] 2021-11-21 17:56
Ah that is strange -- the errors are in mimalloc it seems which should just run fine on freeBSD. Can you try to pull `feature/borrow` and do `git submodule update` to see if the problem is fixed (that branch uses the latest mimalloc). 

Also I see an error in non-mimalloc code for arc4random which should be part of freeBSD; perhaps I missed some include file. I will try to build myself on freeBSD and check.

**Comment by daanx** [comment] 2021-11-21 17:57
ps. You may also be able to work around the issues by passing `-fstdalloc` to Koka; not sure.

**Comment by daanx** [comment] 2021-11-22 05:30
It turned out it had to do with `_DEFAULT_SOURCE` defines and was tricky to resolve :-(  But I checked in a fix and the latest `feature/borrow` branch seems to work  (except for the `std/text/unicode` module due to another bug, hope to resolve that soon). Let me know how it goes :-)

**Comment by devosalain** [comment] 2021-11-22 22:06
I'm not that technical skilled.
I did a 
git pull feature/borrow
fatal: 'feature/borrow' does not appear to be a git repository
in the kaka git clone.

**Comment by melted** [comment] 2021-11-23 10:22
> I'm not that technical skilled. I did a git pull feature/borrow fatal: 'feature/borrow' does not appear to be a git repository in the kaka git clone.

You probably forgot an `origin`: it's `git pull origin feature/borrow`

**Comment by daanx** [comment] 2021-11-23 20:19
Ah sorry @devosalain -- you are brave to use FreeBSD  :-) 
For branches just use checkout, like:
```
$ git checkout feature/borrow
$ git pull
$ cabal new-build
$ cabal new-run koka
```

**Comment by devosalain** [comment] 2021-11-26 12:36
Other issues, giving up.

**Comment by daanx** [comment] 2021-11-27 02:01
No worries. If you get re-inspired, perhaps try the binary release that I created (v2.3.6).

**Closed by daanx** 2021-11-27 02:01 UTC
