### ISSUE TITLE
Anyother compiler error was encountered

### ISSUE THREAD

**Issue by BrendanMesters** [koka-lang/koka#275] opened 2022-06-01 13:32 UTC
I encountered another compiler error.
```
koka analysis-structure.kk  -e
compile: analysis-structure.kk
loading: std/core
loading: std/core/types
loading: std/core/hnd
loading: language-constructs
loading: error-warning-handler
compile: type-functional-effect.kk
loading: scope
check  : type-functional-effect
*** internal compiler error: Type.TypeVar.subFind: incompatible kind: 
 tvar: 1005:KCon V,
 type: TVar (TypeVar {typevarId = 1018, typevarKind = KCon E, typevarFlavour = Skolem}):KCon E
```

The code that produced this error can be found in [This](https://github.com/BrendanMesters/Koka-Linter/commit/1dd97c307a37d7691c5252e7a559187b82c8c094) commit. 

To get the error I tried to compile `analysis-structure.kk`, I assume the bug to appear due to the function `interpreter_handler` in `type-functional-effects.kk`

Good luck with the bug hunting :-)

**Comment by daanx** [comment] 2022-06-01 15:15
Yikes -- that is not good; It is from the internal "core linter". Do you get this error with the latest `dev` branch? I just fixed a kinding error there a week ago.  
I will try to get to it but it is a busy week; do you have a workaround? If you can build Koka yourself you can just comment out the assertion since often the code just works anyways.

**Comment by jmanuel1** [comment] 2022-07-27 07:25
I encountered a very similar error just recently. I built koka from the master branch and didn't get the error after a bit of testing.

**Comment by TimWhiting** [comment] 2024-01-04 06:19
@BrendanMesters  I just checked out that commit, and on the latest release of Koka I was not able to reproduce the error. @jmanuel1 have you seen this or been able to reproduce this recently? If not, maybe we can close this issue.

**Comment by jmanuel1** [comment] 2024-03-31 09:00
@TimWhiting I haven't used Koka in months, and I can tell a lot of work has been done 😆. But I will try to (remember how to) reproduce the bug again soon

**Comment by BrendanMesters** [comment] 2024-05-25 12:08
@TimWhiting its also been a good while for me since I used Koka and have started my system from clean since, so I don't think that I'll be able to reproduce these errors anymore, given the fact that I don't really know what triggered the error.

I do know that it came about when I tried to layer many abstraction levels using the effect handelers (I was doing some research into wether effect handlers could abstract away some of the similar structural elements within compilers, interpreters, and some of the other tools within the compiler pipeline).

I hope that this info might be of help.

**Comment by jmanuel1** [comment] 2024-07-20 00:46
@TimWhiting I don't have the code I wrote to reproduce the error either. But I think at the time I was trying to write an effect signature that had a type parameter, and maybe an effect row parameter, like `effect async<e, a> ...`.

For what it's worth, I downloaded Brendan's code, and with Koka 3.1.2 in WSL, I do not get an ICE on the files he mentioned.

**Comment by TimWhiting** [comment] 2024-12-21 04:35
Closing, since there seems to be nothing actionable left here.

**Closed by TimWhiting** 2024-12-21 04:35 UTC
