### ISSUE TITLE
Incredibly huge memory usage when compiling

### ISSUE THREAD

**Issue by Pauan** [koka-lang/koka#34] opened 2017-06-25 07:01 UTC
When running this command:

```
koka --include="lib" --compile --library --outdir="build" --target="js" "toc.kk"
```

The Koka compiler very rapidly consumes 4 GiB of RAM.

**Comment by maelvalais** [comment] 2017-06-25 11:55
Hi!

I reported the [very same issue](https://github.com/koka-lang/madoko/issues/10) when compiling madoko. Seems to be related to GHC 8 but I reproduced the same memory leak on GHC 7.10. 

The same issue has also been reported in [ghc-mod](https://github.com/DanielG/ghc-mod/issues/834) and a ticket has been [opened](https://ghc.haskell.org/trac/ghc/ticket/13110) in the official GHC issue tracker but it has not been updated for 2 months now.

**Comment by Pauan** [comment] 2017-06-26 01:04
@maelvalais Thanks for the information. It does indeed sound like it's caused by GHC.

**Comment by TimWhiting** [comment] 2024-12-21 02:40
This should be mostly fixed now. We use better strictness annotations, etc. Since it has been a long time since this issue was raised, I'm going to close it. If you run into more memory usage issues, let us know with more up to date reproducible examples.

**Closed by TimWhiting** 2024-12-21 02:40 UTC
Labels: compiler-performance
