### ISSUE TITLE
Internal compiler error ("label is not a constant") where single-letter effect is in angle brackets

### ISSUE THREAD

**Issue by JanBeh** [koka-lang/koka#353] opened 2023-08-03 18:42 UTC
The following program causes a compiler error on Koka `2.4.2`:

```
fun x() : <e> ()
  ()
```

Output:

```
*** internal compiler error: Type.Type.labelNameEx: label is not a constant
```

**Comment by JanBeh** [comment] 2023-08-03 18:43
Possibly related:

* #60

**Comment by evertedsphere** [comment] 2023-08-31 20:51
The cause of this is:

```
tid
  = do (id,rng) <- qvarid <|> typeidCtx
       return (if isTypeVar id then TpVar id rng else TpCon id rng)
  <|>
    do (id,rng) <- wildcard <?> ""
       return (TpVar id rng)
```

where `isTypeVar` [generalises incorrectly](https://github.com/koka-lang/koka/blob/b3122869ac74bfb6f432f7e76eeb723b1f69a491/src/Syntax/Lexeme.hs#L24) in the presence of type variables that are a single lowercase letter:

```hs
isTypeVar :: Name -> Bool
isTypeVar name
  = case nameId name of
      (c:cs) -> (isLower c && all isDigit cs)
      _      -> False
```

I'm not sure what the intention is here (I'm new to Koka and this issue is my first time looking around). If this is intended to handle metavariables or similar (given that digits at the end are allowed), perhaps the numeric suffix could be required to be nonempty. If this is intended to allow for automatic universal quantification (à la Haskell), it seems unintuitive for it to be restricted to single-character type variables.

cc @b-studios

**Comment by TimWhiting** [comment] 2023-09-20 20:50
I have run into the pain point of only being able to use single-character type variables, and from my experience, this is intended to allow for automatic universal quantification.

For a normal function a forall looks like this I think:
```koka
fun first<a>(x: list<a>, y: a): a
  x.head.default(y)
```
Note that having a forall in the parameters seems to require an annotation for the return value as well if it depends on an argument that contains forall type.

**Comment by TimWhiting** [comment] 2023-12-30 10:30
This is fixed on dev and will be in the next release

**Closed** 2024-01-02 13:11 UTC
