### ISSUE TITLE
[BUG] Cannot compile absolute paths

### ISSUE THREAD

**Issue by Pauan** [koka-lang/koka#33] opened 2017-06-25 06:58 UTC
There are two broken situations:

1. The file path breaks if it's absolute. This command:

   ```
   koka --compile --library --outdir="build" --target="js" "/absolute/path/to/koka/lib/toc.kk"
   ```

   Fails with this error:

   ```
   error: could not find: /absolute/path/to/koka/lib/toc.kk
   search path: <empty>
   ```

2. The `--include` flag breaks if it's absolute. This command:

   ```
   koka --include="/absolute/path/to/koka/lib" --compile --library --outdir="build" --target="js" "toc.kk"
   ```

   Fails with this error:

   ```
   error: could not find: toc.kk
   search path: /absolute/path/to/koka/lib
   ```

This is causing problems for Nix, because Nix stores everything in `/nix/store/`, so the Koka compiler can't find any files which are managed by Nix.

**Comment by sternenseemann** [comment] 2020-09-06 21:11
Should be fixed by now, can't reproduce. At least via #93, but is also resolved on `master` probably (can't test right now).

**Closed** 2024-01-02 18:37 UTC
